name: Publish Release

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3.11 -
        poetry install

    - name: Build and publish
      run: |
        poetry config pypi-token.pypi '${{ secrets.PYPI_API_TOKEN }}'
        poetry publish --build
